---

language: bash
dist: bionic

env:
  global:
    - MY_GLOBAL_ENVIRONMENT_VARIABLE=global_myenv
  matrix:
    - MY_ENVIRONMENT_VARIABLE=myenv_1
    - MY_ENVIRONMENT_VARIABLE=myenv_2

jobs:
  include:
    - script:
        - echo $MY_GLOBAL_ENVIRONMENT_VARIABLE
        - echo $MY_ENVIRONMENT_VARIABLE
      env:
        - MY_GLOBAL_ENVIRONMENT_VARIABLE=hey
        - MY_ENVIRONMENT_VARIABLE=hoy
