---

language: python
dist: bionic
python:
  - 3.7

env:
  global:
    MY_GLOBAL_ENVIRONMENT_VARIABLE: global_myenv
  matrix:
    MY_ENVIRONMENT_VARIABLE: myenv_1
    MY_ENVIRONMENT_VARIABLE: myenv_2

jobs:
  include:
    - stage: test_1
      script:
        - echo $hoge
        - echo $piyo
      env:
        hoge: HOGE
        piyo: PIYO
    - stage: test_2
      script:
        - echo $MY_GLOBAL_ENVIRONMENT_VARIABLE
        - echo $MY_ENVIRONMENT_VARIABLE
        - echo $hoge_1
        - echo $piyo_2
      env:
        global:
          piyo_2: PIYO_2
        matrix:
          hoge_1: HOGE_1
          hoge_1: HOGE_2

script:
  - echo HOGEHOGE
