---

language: python
dist: bionic
python:
  - 3.7

env:
  global:
    MY_GLOBAL_ENVIRONMENT_VARIABLE: global_myenv
  matrix:
    MY_ENVIRONMENT_VARIABLE: myenv_1
    MY_ENVIRONMENT_VARIABLE: myenv_2

jobs:
  include:
    - stage: test_1
      script:
        - echo $HOGE
        - echo $PIYO
      env:
        hoge: HOGE
        piyo: PIYO

script:
  - echo HOGEHOGE
