---

language: bash

env:
  global:
    - MY_GLOBAL_ENVIRONMENT_VARIABLE=global_myenv
  matrix:
    - MY_ENVIRONMENT_VARIABLE=myenv_1
    - MY_ENVIRONMENT_VARIABLE=myenv_2
    - MY_ENVIRONMENT_VARIABLE=myenv_3

script:
  - echo $MY_GLOBAL_ENVIRONMENT_VARIABLE
  - echo $MY_ENVIRONMENT_VARIABLE
